<a href="https://colab.research.google.com/github/Marcus-Borges/Execicio-Una_IA/blob/main/IA_Una.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

import pandas as pd



# Criando um DataFrame de exemplo

data = {'Idade': [25, 30, 45, 22, 23],

        'Salário': [50000, 60000, 80000, 120000, 110000],

        'Comprou': ['Sim', 'Não', 'Sim', 'Não', 'Sim']}



df = pd.DataFrame(data)


# Visualizar os primeiros registros

print(df.head())



# Transformar a coluna "Comprou" em variáveis numéricas (Sim=1, Não=0)

df['Comprou'] = df['Comprou'].apply(lambda x: 1 if x == 'Sim' else 0)



# Converter os dados em matriz NumPy

X = df[['Idade', 'Salário']].values

y = df['Comprou'].values



print("Matriz de atributos X:\n", X)

print("Vetor alvo y:\n", y)

   Idade  Salário Comprou
0     25    50000     Sim
1     30    60000     Não
2     45    80000     Sim
3     22   120000     Não
4     23   110000     Sim
Matriz de atributos X:
 [[    25  50000]
 [    30  60000]
 [    45  80000]
 [    22 120000]
 [    23 110000]]
Vetor alvo y:
 [1 0 1 0 1]


In [2]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score



# Dividir o conjunto de dados em treino e teste

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



# Instanciar o modelo de regressão logística

model = LogisticRegression()



# Treinar o modelo

model.fit(X_train, y_train)



# Fazer previsões

y_pred = model.predict(X_test)



# Avaliar a precisão do modelo

accuracy = accuracy_score(y_test, y_pred)

print(f"Acurácia do modelo: {accuracy * 100:.2f}%")

Acurácia do modelo: 0.00%


In [3]:
import tensorflow as tf

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense

# Normalizar os dados de entrada

X_train = X_train / np.max(X_train, axis=0)

X_test = X_test / np.max(X_test, axis=0)

# Definir o modelo de rede neural

model = Sequential()

# Adicionar camadas (entrada com 2 neurônios, 1 camada escondida com 5 neurônios, e uma saída com 1 neurônio)

model.add(Dense(5, input_dim=2, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

# Compilar o modelo

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Treinar o modelo

model.fit(X_train, y_train, epochs=50, batch_size=10, verbose=1)

# Avaliar o modelo no conjunto de teste

loss, accuracy = model.evaluate(X_test, y_test)

print(f"Acurácia do modelo com rede neural: {accuracy * 100:.2f}%")

Epoch 1/50


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.2500 - loss: 0.8726
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2500 - loss: 0.8708
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2500 - loss: 0.8691
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2500 - loss: 0.8673
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2500 - loss: 0.8656
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2500 - loss: 0.8639
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.2500 - loss: 0.8621
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.2500 - loss: 0.8604
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2500 - loss: 0.8587
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2500 - loss: 0.8570
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.2500 - loss: 0.8553
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.2500 - loss: 0.8536
Epoch 13/50
1/

In [9]:
import pandas as pd
import numpy as np

# Dados fictícios
data = {
    'Idade': [25, 30, 45, 22, 23],
    'Salário': [50000, 60000, None, 120000, 110000],
    'Contratado': ['Sim', 'Não', 'Sim', 'Não', 'Sim']
}

# 1. Carregar os dados em um DataFrame com Pandas
df = pd.DataFrame(data)


# 2. Preencher os valores ausentes (NaN) na coluna "Salário" com a média dos salários existentes
df['Salário'].fillna(df['Salário'].mean(), inplace=True)

print(df.head())

# 3. Converter a coluna "Contratado" em valores binários (Sim = 1, Não = 0)
df['Contratado'] = df['Contratado'].map({'Sim': 1, 'Não': 0})

# 4. Extrair as colunas "Idade" e "Salário" como uma matriz NumPy e a coluna "Contratado" como vetor
X = df[['Idade', 'Salário']].values  # Matriz NumPy com "Idade" e "Salário"
y = df['Contratado'].values  # Vetor alvo com "Contratado"

# Exibir resultados
print("Matriz de atributos X:\n", X)

print("Vetor alvo y:\n", y)


   Idade   Salário Contratado
0     25   50000.0        Sim
1     30   60000.0        Não
2     45   85000.0        Sim
3     22  120000.0        Não
4     23  110000.0        Sim
Matriz de atributos X:
 [[2.5e+01 5.0e+04]
 [3.0e+01 6.0e+04]
 [4.5e+01 8.5e+04]
 [2.2e+01 1.2e+05]
 [2.3e+01 1.1e+05]]
Vetor alvo y:
 [1 0 1 0 1]


In [10]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score



# Dividir o conjunto de dados em treino e teste

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



# Instanciar o modelo de regressão logística

model = LogisticRegression()



# Treinar o modelo

model.fit(X_train, y_train)



# Fazer previsões

y_pred = model.predict(X_test)



# Avaliar a precisão do modelo

accuracy = accuracy_score(y_test, y_pred)

print(f"Acurácia do modelo: {accuracy * 100:.2f}%")

Acurácia do modelo: 0.00%


In [11]:
import tensorflow as tf

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense

# Normalizar os dados de entrada

X_train = X_train / np.max(X_train, axis=0)

X_test = X_test / np.max(X_test, axis=0)

# Definir o modelo de rede neural

model = Sequential()

# Adicionar camadas (entrada com 2 neurônios, 1 camada escondida com 5 neurônios, e uma saída com 1 neurônio)

model.add(Dense(5, input_dim=2, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

# Compilar o modelo

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Treinar o modelo

model.fit(X_train, y_train, epochs=50, batch_size=10, verbose=1)

# Avaliar o modelo no conjunto de teste

loss, accuracy = model.evaluate(X_test, y_test)

print(f"Acurácia do modelo com rede neural: {accuracy * 100:.2f}%")

Epoch 1/50


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 868ms/step - accuracy: 0.2500 - loss: 0.7652
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.2500 - loss: 0.7644
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.7636
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.2500 - loss: 0.7627
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2500 - loss: 0.7619
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.2500 - loss: 0.7611
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.7603
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.2500 - loss: 0.7595
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.2500 - loss: 0.7587
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2500 - loss: 0.7579
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2500 - loss: 0.7571
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2500 - loss: 0.7563
Epoch 13/50

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Dados fictícios
data = {
    'Nota1': [85, 62, 78, 95, 55, 40, 60, 90],
    'Nota2': [88, 65, 74, 90, 60, 42, 70, 85],
    'Aprovado': [1, 0, 1, 1, 0, 0, 0, 1]
}

# 1. Carregar os dados em um DataFrame
df = pd.DataFrame(data)

# Definir as variáveis independentes (X) e a variável alvo (y)
X = df[['Nota1', 'Nota2']]  # Notas como atributos
y = df['Aprovado']  # Aprovado como alvo

# 2. Dividir os dados em conjunto de treino e teste (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Treinar o modelo de Regressão Logística
model = LogisticRegression()
model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = model.predict(X_test)

# 4. Calcular a acurácia do modelo
accuracy = accuracy_score(y_test, y_pred)

# Exibir resultados
print("Acurácia do modelo:", accuracy)


print("Previsões:", y_pred)
print("Valores Reais:", y_test.values)


Acurácia do modelo: 1.0
Previsões: [0 0]
Valores Reais: [0 0]
